<?php
//subtraction

$x=17;
$y=2;
echo"subtraction". ($x-=$y);
echo("<br>");

$x=17;
$y=2;
echo"modules". ($x%=$y);


echo("<br>");



$grade = ("grade") ;
    

    
$grade = 76;


if($grade >=90 && $grade <= 100){
    
    
    
    echo "exelent";
         }


elseif($grade >=80 && $grade <=89) {


    echo "very good";
}
 






elseif($grade>=70 && $grade<=79) 
   

echo "good";





    elseif($grade >=60 && $grade <=69) 



    echo "medium";






        elseif($grade >=50 && $grade <=59) 



        echo "pass";
    







            elseif($grade >=0 && $grade <=49) 



            echo "fail";



                else 



                echo "not defined";









 
$a=1;

while ($a<=10){

   if ($a%2==0)

{
echo "odd";
}
echo $a."<br>";
$a++;
}
?>
